/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import Usuario.Usuario;
import GestorDatosPermanentes.BaseDeDatos;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.time.LocalDate;
import java.util.HashMap;
import Login.MantenimientoLogin;
import MenuDinamico.FrmMenuDinamico;
import MenuDinamico.FrmMenuDinamico;

public class FrmLogin extends javax.swing.JFrame {

    private BaseDeDatos baseDeDatos;

    public FrmLogin() {
        setTitle("Sistema de Inventario - Agro Integral");
        setSize(400, 250);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        initComponents();
        baseDeDatos = new BaseDeDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLoginHolder = new javax.swing.JPanel();
        jPanelLogin = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        txfUsuario = new javax.swing.JTextField();
        txfContraseña = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblDecoracion2 = new javax.swing.JLabel();
        lblDecoracion1 = new javax.swing.JLabel();
        lblLogoEmpresa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Inventario - Agro Integral");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelLoginHolder.setBackground(new java.awt.Color(56, 141, 165));
        jPanelLoginHolder.setLayout(null);

        jPanelLogin.setLayout(null);

        lblLogin.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblLogin.setText("LOGIN");
        jPanelLogin.add(lblLogin);
        lblLogin.setBounds(33, 14, 65, 30);

        txfUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanelLogin.add(txfUsuario);
        txfUsuario.setBounds(102, 91, 220, 35);

        txfContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanelLogin.add(txfContraseña);
        txfContraseña.setBounds(102, 180, 220, 35);

        btnIngresar.setBackground(new java.awt.Color(51, 51, 51));
        btnIngresar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanelLogin.add(btnIngresar);
        btnIngresar.setBounds(19, 266, 303, 38);

        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        jPanelLogin.add(lblUsuario);
        lblUsuario.setBounds(19, 79, 65, 47);

        lblContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contraseña.png"))); // NOI18N
        jPanelLogin.add(lblContraseña);
        lblContraseña.setBounds(19, 153, 65, 73);

        lblDecoracion2.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lblDecoracion2.setText("_________________");
        jPanelLogin.add(lblDecoracion2);
        lblDecoracion2.setBounds(200, 310, 130, 16);

        lblDecoracion1.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lblDecoracion1.setText("_________________");
        jPanelLogin.add(lblDecoracion1);
        lblDecoracion1.setBounds(20, 310, 130, 18);

        jPanelLoginHolder.add(jPanelLogin);
        jPanelLogin.setBounds(336, 19, 350, 400);

        lblLogoEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoEmpresa removebg.png"))); // NOI18N
        jPanelLoginHolder.add(lblLogoEmpresa);
        lblLogoEmpresa.setBounds(10, 100, 320, 220);

        getContentPane().add(jPanelLoginHolder);
        jPanelLoginHolder.setBounds(0, 0, 719, 472);

        setSize(new java.awt.Dimension(735, 481));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Regresa la contraseña creada
    private String obligarCrearContraseña(String contraseñaAntigua) {
        String[] options = {"OK"};
        JPanel JPanelPedirContraNueva = new JPanel();
        JLabel lblPedirNuevaContraseña = new JLabel("Pasaron más de 60 días. Cree una nueva contraseña:");
        JTextField txfNuevaContra = new JTextField(15);
        JPanelPedirContraNueva.add(lblPedirNuevaContraseña);
        JPanelPedirContraNueva.add(txfNuevaContra);
        String contraseñaNueva;
        do {

            JOptionPane.showOptionDialog(this, JPanelPedirContraNueva, "Creando contraseña", JOptionPane.NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            contraseñaNueva = txfNuevaContra.getText();
            if (!MantenimientoLogin.esContraseñaValida(txfNuevaContra.getText())) {
                JOptionPane.showMessageDialog(this, "Formato de contraseña incorrecto. Intente de nuevo");
                continue;
            } else if (contraseñaAntigua.equals(contraseñaNueva)) {
                JOptionPane.showMessageDialog(this, "La contraseña debe ser distinta a la anterior.");
                continue;
            }
            break;
        } while (true);
        return txfNuevaContra.getText();
    }

    private void interpretarRespuesta(int respuesta) {
        switch (respuesta) {
            case BaseDeDatos.USUARIO_CONTRA_INCORRECTOS:
                JOptionPane.showMessageDialog(this, "Intento de Login, Error: Usuario o contraseña incorrecto");
                break;
            case BaseDeDatos.USUARIO_BLOQUEADO:
                JOptionPane.showMessageDialog(this, "Intento de Login, Error: Usuario bloqueado");
                break;
            case BaseDeDatos.DEBE_CAMBIAR_CONTRASEÑA:
                if (baseDeDatos.actualizarContraseña(txfUsuario.getText(), txfContraseña.getText(), obligarCrearContraseña(txfContraseña.getText()))) {
                    JOptionPane.showMessageDialog(this, "La contraseña se cambio correctamente");
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo cambiar la contraseña");
                }
                break;
            default:
                JOptionPane.showMessageDialog(this, "Intento de Login, Error: no definido");
                break;
        }
    }

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        //usuario de prueba
        String DNIoRUC = txfUsuario.getText(), contraseña = txfContraseña.getText();

        if (!MantenimientoLogin.esDniORucValido(DNIoRUC) || !MantenimientoLogin.esContraseñaValida(contraseña)) {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos. Intente de nuevo");
            return;
        }
        Object[] respuestaDB = baseDeDatos.intentarLogin(DNIoRUC, contraseña);

        if ((int) respuestaDB[0] == BaseDeDatos.PUEDE_INGRESAR) {
            dispose();
            FrmMenuDinamico menu = new FrmMenuDinamico();
            menu.modificarSegunRol((Usuario) respuestaDB[1]);
            menu.setVisible(true);

        } else {
            interpretarRespuesta((int) respuestaDB[0]);
        }

    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelLoginHolder;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblDecoracion1;
    private javax.swing.JLabel lblDecoracion2;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogoEmpresa;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txfContraseña;
    private javax.swing.JTextField txfUsuario;
    // End of variables declaration//GEN-END:variables
}
