/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Usuario;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ORLANDO
 */
public class FrmMenuDinamico extends javax.swing.JFrame {

    /**
     * Creates new form MenuDinamico
     */
    public FrmMenuDinamico() {
        initComponents();
        jpaneladmin.setVisible(false);

    }

    public void modificarSegunRol(Usuario usuario) {
        if (usuario.getRol().equalsIgnoreCase("administrador")) {
            jpaneladmin.setVisible(true);
            jpaneladmin.setEnabled(true);
        }
        lblRol.setText(usuario.getRol());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelgeneral = new javax.swing.JPanel();
        jpaneladmin = new javax.swing.JPanel();
        btncaja = new javax.swing.JLabel();
        btnregistrodeusuario = new javax.swing.JLabel();
        btnreportes = new javax.swing.JLabel();
        btnajustes = new javax.swing.JLabel();
        btninicio = new javax.swing.JLabel();
        btnAlmacen = new javax.swing.JLabel();
        btnregistrodecompras = new javax.swing.JLabel();
        btnregistrodeventas = new javax.swing.JLabel();
        btncerrarsesion = new javax.swing.JLabel();
        jpanelsuperior = new javax.swing.JPanel();
        lblinventario = new javax.swing.JLabel();
        lblimagen1 = new javax.swing.JLabel();
        lblimagen2 = new javax.swing.JLabel();
        lblRUC = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jpanelgeneral.setBackground(new java.awt.Color(0, 153, 153));
        jpanelgeneral.setLayout(null);

        jpaneladmin.setBackground(new java.awt.Color(0, 153, 153));
        jpaneladmin.setEnabled(false);
        jpaneladmin.setLayout(null);

        btncaja.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btncaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dinero.png"))); // NOI18N
        btncaja.setText("CAJA");
        btncaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncajaMouseClicked(evt);
            }
        });
        jpaneladmin.add(btncaja);
        btncaja.setBounds(70, 10, 140, 50);

        btnregistrodeusuario.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnregistrodeusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/personas.png"))); // NOI18N
        btnregistrodeusuario.setText("REGISTRO DE USUARIOS");
        btnregistrodeusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistrodeusuarioMouseClicked(evt);
            }
        });
        jpaneladmin.add(btnregistrodeusuario);
        btnregistrodeusuario.setBounds(0, 70, 280, 60);

        btnreportes.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnreportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/documento.png"))); // NOI18N
        btnreportes.setText("REPORTES");
        btnreportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnreportesMouseClicked(evt);
            }
        });
        jpaneladmin.add(btnreportes);
        btnreportes.setBounds(60, 130, 170, 50);

        btnajustes.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnajustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuercas.png"))); // NOI18N
        btnajustes.setText("AJUSTES");
        btnajustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnajustesMouseClicked(evt);
            }
        });
        jpaneladmin.add(btnajustes);
        btnajustes.setBounds(60, 180, 170, 50);

        jpanelgeneral.add(jpaneladmin);
        jpaneladmin.setBounds(0, 220, 280, 250);

        btninicio.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btninicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        btninicio.setText("INICIO");
        btninicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btninicioMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btninicio);
        btninicio.setBounds(70, 10, 140, 50);

        btnAlmacen.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caja.png"))); // NOI18N
        btnAlmacen.setText("ALMACEN");
        btnAlmacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlmacenMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btnAlmacen);
        btnAlmacen.setBounds(60, 60, 160, 50);

        btnregistrodecompras.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnregistrodecompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/camion.png"))); // NOI18N
        btnregistrodecompras.setText("REGISTRO DE COMPRAS");
        btnregistrodecompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistrodecomprasMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btnregistrodecompras);
        btnregistrodecompras.setBounds(10, 110, 280, 50);

        btnregistrodeventas.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnregistrodeventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tienda.png"))); // NOI18N
        btnregistrodeventas.setText("REGISTRO DE VENTAS");
        btnregistrodeventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistrodeventasMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btnregistrodeventas);
        btnregistrodeventas.setBounds(10, 160, 270, 50);

        btncerrarsesion.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btncerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/puerta.png"))); // NOI18N
        btncerrarsesion.setText("CERRAR SESION");
        btncerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncerrarsesionMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btncerrarsesion);
        btncerrarsesion.setBounds(40, 460, 210, 50);

        getContentPane().add(jpanelgeneral);
        jpanelgeneral.setBounds(0, 80, 280, 530);

        jpanelsuperior.setBackground(new java.awt.Color(0, 153, 153));
        jpanelsuperior.setLayout(null);

        lblinventario.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        lblinventario.setText("INVENTARIO");
        jpanelsuperior.add(lblinventario);
        lblinventario.setBounds(20, 20, 180, 30);

        lblimagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carretilla.png"))); // NOI18N
        jpanelsuperior.add(lblimagen1);
        lblimagen1.setBounds(190, 10, 70, 60);

        lblimagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuariovl2.png"))); // NOI18N
        jpanelsuperior.add(lblimagen2);
        lblimagen2.setBounds(810, 20, 50, 40);

        lblRUC.setFont(new java.awt.Font("Cartoon Fun", 0, 14)); // NOI18N
        lblRUC.setText("Agro Integral Perú");
        jpanelsuperior.add(lblRUC);
        lblRUC.setBounds(610, 10, 200, 24);

        lblRol.setText("Empleado");
        jpanelsuperior.add(lblRol);
        lblRol.setBounds(650, 40, 150, 16);

        getContentPane().add(jpanelsuperior);
        jpanelsuperior.setBounds(0, 0, 880, 80);

        setSize(new java.awt.Dimension(894, 644));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarNombre(JLabel label) {
        JOptionPane.showMessageDialog(this, "el boton" + label.getText() + " FUNCIONA!!!");
    }

    private void btninicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninicioMouseClicked
        // TODO add your handling code here:
        mostrarNombre(btninicio);
    }//GEN-LAST:event_btninicioMouseClicked

    private void btnAlmacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlmacenMouseClicked
        // TODO add your handling code here:
        mostrarNombre(btnAlmacen);
    }//GEN-LAST:event_btnAlmacenMouseClicked

    private void btnregistrodecomprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrodecomprasMouseClicked
        // TODO add your handling code here:
        mostrarNombre(btnAlmacen);
    }//GEN-LAST:event_btnregistrodecomprasMouseClicked

    private void btnregistrodeventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrodeventasMouseClicked
        // TODO add your handling code here:
        mostrarNombre(btnregistrodeventas);
    }//GEN-LAST:event_btnregistrodeventasMouseClicked

    private void btncajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncajaMouseClicked
        // TODO add your handling code here:
        mostrarNombre(btncaja);
    }//GEN-LAST:event_btncajaMouseClicked

    private void btnregistrodeusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrodeusuarioMouseClicked
        // TODO add your handling code here:
        mostrarNombre(btnregistrodeusuario);
    }//GEN-LAST:event_btnregistrodeusuarioMouseClicked

    private void btnreportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreportesMouseClicked
        // TODO add your handling code here:
        mostrarNombre(btnreportes);
    }//GEN-LAST:event_btnreportesMouseClicked

    private void btnajustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajustesMouseClicked
        // TODO add your handling code here:
        mostrarNombre(btnajustes);
    }//GEN-LAST:event_btnajustesMouseClicked

    private void btncerrarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarsesionMouseClicked
        // TODO add your handling code here:
        mostrarNombre(btncerrarsesion);
    }//GEN-LAST:event_btncerrarsesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuDinamico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAlmacen;
    private javax.swing.JLabel btnajustes;
    private javax.swing.JLabel btncaja;
    private javax.swing.JLabel btncerrarsesion;
    private javax.swing.JLabel btninicio;
    private javax.swing.JLabel btnregistrodecompras;
    private javax.swing.JLabel btnregistrodeusuario;
    private javax.swing.JLabel btnregistrodeventas;
    private javax.swing.JLabel btnreportes;
    private javax.swing.JPanel jpaneladmin;
    private javax.swing.JPanel jpanelgeneral;
    private javax.swing.JPanel jpanelsuperior;
    private javax.swing.JLabel lblRUC;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblimagen1;
    private javax.swing.JLabel lblimagen2;
    private javax.swing.JLabel lblinventario;
    // End of variables declaration//GEN-END:variables
}
