/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author ORLANDO
 */
public class MenuDinamico extends javax.swing.JFrame {
    /**
     * Creates new form MenuDinamico
     */
    public MenuDinamico() {
        initComponents();
        jpaneladmin.setVisible(false);
        
    }
    public void MostrarBotonesAdministrador()
    {
        jpaneladmin.setVisible(true);
        jpaneladmin.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelgeneral = new javax.swing.JPanel();
        btninicio = new javax.swing.JButton();
        btnregistrodeventas = new javax.swing.JButton();
        btnalmacen = new javax.swing.JButton();
        btnregistrodecompras = new javax.swing.JButton();
        btncerrarsesion = new javax.swing.JButton();
        jpaneladmin = new javax.swing.JPanel();
        btncaja = new javax.swing.JButton();
        btnajustes = new javax.swing.JButton();
        btnregistrodeusuario = new javax.swing.JButton();
        btnreportes = new javax.swing.JButton();
        jpanelsuperior = new javax.swing.JPanel();
        lblinventario = new javax.swing.JLabel();
        lblimagen1 = new javax.swing.JLabel();
        lblimagen2 = new javax.swing.JLabel();
        lblRUC = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jpanelgeneral.setBackground(new java.awt.Color(64, 147, 164));
        jpanelgeneral.setLayout(null);

        btninicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        btninicio.setText("INICIO");
        btninicio.setContentAreaFilled(false);
        jpanelgeneral.add(btninicio);
        btninicio.setBounds(20, 10, 220, 40);

        btnregistrodeventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tienda.png"))); // NOI18N
        btnregistrodeventas.setText("REGISTRO DE VENTAS");
        btnregistrodeventas.setContentAreaFilled(false);
        jpanelgeneral.add(btnregistrodeventas);
        btnregistrodeventas.setBounds(20, 170, 220, 50);

        btnalmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caja.png"))); // NOI18N
        btnalmacen.setText("ALMACEN");
        btnalmacen.setContentAreaFilled(false);
        jpanelgeneral.add(btnalmacen);
        btnalmacen.setBounds(20, 60, 220, 50);

        btnregistrodecompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/camion.png"))); // NOI18N
        btnregistrodecompras.setText("REGISTRO DE COMPRAS");
        btnregistrodecompras.setContentAreaFilled(false);
        jpanelgeneral.add(btnregistrodecompras);
        btnregistrodecompras.setBounds(20, 120, 220, 40);

        btncerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/puerta.png"))); // NOI18N
        btncerrarsesion.setText("CERRAR SESION");
        btncerrarsesion.setContentAreaFilled(false);
        jpanelgeneral.add(btncerrarsesion);
        btncerrarsesion.setBounds(20, 460, 220, 50);

        jpaneladmin.setBackground(new java.awt.Color(64, 147, 164));
        jpaneladmin.setEnabled(false);
        jpaneladmin.setLayout(null);

        btncaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dinero.png"))); // NOI18N
        btncaja.setText("CAJA");
        btncaja.setContentAreaFilled(false);
        jpaneladmin.add(btncaja);
        btncaja.setBounds(20, 10, 220, 50);

        btnajustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuercas.png"))); // NOI18N
        btnajustes.setText("AJUSTES");
        btnajustes.setContentAreaFilled(false);
        jpaneladmin.add(btnajustes);
        btnajustes.setBounds(20, 190, 220, 50);

        btnregistrodeusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/personas.png"))); // NOI18N
        btnregistrodeusuario.setText("REGISTRO DE USUARIOS");
        btnregistrodeusuario.setContentAreaFilled(false);
        jpaneladmin.add(btnregistrodeusuario);
        btnregistrodeusuario.setBounds(20, 70, 220, 50);

        btnreportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/documento.png"))); // NOI18N
        btnreportes.setText("REPORTES");
        btnreportes.setContentAreaFilled(false);
        jpaneladmin.add(btnreportes);
        btnreportes.setBounds(20, 130, 220, 50);

        jpanelgeneral.add(jpaneladmin);
        jpaneladmin.setBounds(0, 220, 250, 250);

        getContentPane().add(jpanelgeneral);
        jpanelgeneral.setBounds(0, 90, 250, 520);

        jpanelsuperior.setBackground(new java.awt.Color(64, 147, 164));
        jpanelsuperior.setLayout(null);

        lblinventario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblinventario.setText("INVENTARIO");
        jpanelsuperior.add(lblinventario);
        lblinventario.setBounds(20, 20, 160, 30);

        lblimagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/puerta.png"))); // NOI18N
        jpanelsuperior.add(lblimagen1);
        lblimagen1.setBounds(170, 20, 70, 40);

        lblimagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuariovl2.png"))); // NOI18N
        jpanelsuperior.add(lblimagen2);
        lblimagen2.setBounds(810, 20, 50, 40);

        lblRUC.setText("XXXXXXXXXXXXXXXXXXXXX");
        jpanelsuperior.add(lblRUC);
        lblRUC.setBounds(650, 20, 150, 16);

        lblRol.setText("---------------------");
        jpanelsuperior.add(lblRol);
        lblRol.setBounds(650, 40, 150, 16);

        getContentPane().add(jpanelsuperior);
        jpanelsuperior.setBounds(0, 0, 880, 80);

        setSize(new java.awt.Dimension(894, 644));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDinamico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajustes;
    private javax.swing.JButton btnalmacen;
    private javax.swing.JButton btncaja;
    private javax.swing.JButton btncerrarsesion;
    private javax.swing.JButton btninicio;
    private javax.swing.JButton btnregistrodecompras;
    private javax.swing.JButton btnregistrodeusuario;
    private javax.swing.JButton btnregistrodeventas;
    private javax.swing.JButton btnreportes;
    private javax.swing.JPanel jpaneladmin;
    private javax.swing.JPanel jpanelgeneral;
    private javax.swing.JPanel jpanelsuperior;
    private javax.swing.JLabel lblRUC;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblimagen1;
    private javax.swing.JLabel lblimagen2;
    private javax.swing.JLabel lblinventario;
    // End of variables declaration//GEN-END:variables
}
