package MenuDinamico;

import Usuario.Usuario;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import GestorDatosPermanentes.SQLiteManager;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Login.FrmLogin;
import java.time.LocalDate;
import javax.swing.JTable;
import Producto.Producto;
import javax.swing.JTextField;

public class FrmMenuDinamico extends javax.swing.JFrame {

    private Usuario usuario;
    private SQLiteManager baseDeDatos;
    private DefaultTableModel[] listaModelos;
    private String[][] columnas;
    private String[][] listaCols;
    private JTable[] tablas;
    private String[] colsRegUsu = {"Usuario ID", "Empleado", "Usuario", "Contraseña", "Tipo", "Telefono", "Estado"};
    private final int indiceRegUsu = 0;
    private String[] colsRegProd = {"Producto ID", "Tipo de Documento", "Producto", "Precio Compra", "Cantidad", "Stock"};
    private final int indiceRegProd = 1;

    public FrmMenuDinamico() {
        initComponents();
        jpaneladmin.setVisible(false);
        baseDeDatos = new SQLiteManager();
        listaCols = new String[][]{colsRegUsu, colsRegProd};
        tablas = new JTable[]{tblRegistroUsuarios, tblRegistroProductos};
        listaModelos = new DefaultTableModel[tablas.length];
        inicializarModelos();

        //configuracion personalizada para tblRegistroProductos
        listaModelos[indiceRegProd] = new DefaultTableModel(listaCols[indiceRegProd], 0) {
            @Override
            public boolean isCellEditable(int row, int colum) {
                return colum != 0 && colum != 1 && colum != 5;
            }
        };
        tablas[indiceRegProd].setModel(listaModelos[indiceRegProd]);
    }

    private void inicializarModelos() {
        for (int i = 0; i < listaModelos.length; i++) {
            listaModelos[i] = new DefaultTableModel(listaCols[i], 0) {
                @Override
                public boolean isCellEditable(int row, int colum) {
                    return colum != 0;
                }
            };
            tablas[i].setModel(listaModelos[i]);
        }
    }

    public void modificarSegunRol(Usuario usuario) {
        this.usuario = new Usuario(usuario);
        if (this.usuario.getRol().equalsIgnoreCase("administrador")) {
            jpaneladmin.setVisible(true);
            jpaneladmin.setEnabled(true);
        }
        lblRol.setText(usuario.getRol());
    }

    private void actualizarTBLRegistroUsuarios() {

        listaModelos[indiceRegUsu].setRowCount(0);
        ArrayList<Usuario> lista = baseDeDatos.obtenerUsuarios();

        for (Usuario usu : lista) {
            Object[] datoFila = {usu.getUsuario_id(), usu.getNombres() + " " + usu.getApellidos(), usu.getUsuarioDNIoRUC(), usu.getContraseña(), usu.getRol(), usu.getTelefono(), Usuario.parseEsCuentaBloqueada(usu.esCuentaBloqueada())};
            listaModelos[indiceRegUsu].addRow(datoFila);
        }
    }

    private void actualizarTBLRegistroProductos() {

        listaModelos[indiceRegProd].setRowCount(0);
        ArrayList<Producto> lista = baseDeDatos.obtenerProductos();

        for (Producto pro : lista) {
            Object[] datoFila = {pro.getID(), pro.getTipoDocumento(), pro.getProducto(), pro.getPrecioCompra(), pro.getCantidad(), pro.getStock()};
            listaModelos[indiceRegProd].addRow(datoFila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelgeneral = new javax.swing.JPanel();
        jpaneladmin = new javax.swing.JPanel();
        btncaja = new javax.swing.JLabel();
        btnregistrodeusuario = new javax.swing.JLabel();
        btnreportes = new javax.swing.JLabel();
        btnajustes = new javax.swing.JLabel();
        btninicio = new javax.swing.JLabel();
        btnAlmacen = new javax.swing.JLabel();
        btnregistrodecompras = new javax.swing.JLabel();
        btnregistrodeventas = new javax.swing.JLabel();
        btncerrarsesion = new javax.swing.JLabel();
        jpanelsuperior = new javax.swing.JPanel();
        lblinventario = new javax.swing.JLabel();
        lblimagen1 = new javax.swing.JLabel();
        lblimagen2 = new javax.swing.JLabel();
        lblRUC = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        tpnMostrar = new javax.swing.JTabbedPane();
        pnl1Inicio = new javax.swing.JPanel();
        lblSubTitulo = new javax.swing.JLabel();
        pnlProductos = new javax.swing.JPanel();
        lblProductos = new javax.swing.JLabel();
        txtProductos = new javax.swing.JTextField();
        pnlGancias = new javax.swing.JPanel();
        lblGanancias = new javax.swing.JLabel();
        txtGanancias = new javax.swing.JTextField();
        pnlProveedores = new javax.swing.JPanel();
        lblProveedores = new javax.swing.JLabel();
        txtProveedores = new javax.swing.JTextField();
        pnlCompraDelMes = new javax.swing.JPanel();
        lblCompraDelMes = new javax.swing.JLabel();
        txtComprasDelMes = new javax.swing.JTextField();
        pnlVentasDelDia = new javax.swing.JPanel();
        lblVentasDelDia = new javax.swing.JLabel();
        txtVentasDelDia = new javax.swing.JTextField();
        pnlCientes = new javax.swing.JPanel();
        lblClientes = new javax.swing.JLabel();
        txtClientes = new javax.swing.JTextField();
        pnlRegUsuMostrar = new javax.swing.JPanel();
        btnCrearUsuario = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistroUsuarios = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        pnlRegUsuIngresar = new javax.swing.JPanel();
        lblAgregaryCrearUsuario = new javax.swing.JLabel();
        lblSubTitulo1 = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblDNIUsuario = new javax.swing.JLabel();
        txtDNIUsuario = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        lblTipoUsuario = new javax.swing.JLabel();
        cbTipoUsuario = new javax.swing.JComboBox<>();
        btnGuardaryAgregarDatos = new javax.swing.JButton();
        rbtActivo = new javax.swing.JRadioButton();
        rbtInactivo = new javax.swing.JRadioButton();
        pnl1Almacen = new javax.swing.JPanel();
        lblSubtema2 = new javax.swing.JLabel();
        cbTipoStock = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRegistroProductos = new javax.swing.JTable();
        lblPreciodeProducto = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        lblCantidaddeProducto = new javax.swing.JLabel();
        btnBuscarAlmacen = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnAgregarAlmacen = new javax.swing.JButton();
        btnEliminarAlmacen = new javax.swing.JButton();
        btnEditarAlmacen = new javax.swing.JButton();
        txtPreciodeCompra = new javax.swing.JTextField();
        txtProducto = new javax.swing.JTextField();
        txtCantidaddeProducto = new javax.swing.JTextField();
        btnFiltrarAlmacen = new javax.swing.JButton();
        lblImagen1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jpanelgeneral.setBackground(new java.awt.Color(0, 153, 153));
        jpanelgeneral.setLayout(null);

        jpaneladmin.setBackground(new java.awt.Color(0, 153, 153));
        jpaneladmin.setEnabled(false);
        jpaneladmin.setLayout(null);

        btncaja.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btncaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dinero.png"))); // NOI18N
        btncaja.setText("CAJA");
        btncaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncajaMouseClicked(evt);
            }
        });
        jpaneladmin.add(btncaja);
        btncaja.setBounds(0, 0, 140, 50);

        btnregistrodeusuario.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnregistrodeusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/personas.png"))); // NOI18N
        btnregistrodeusuario.setText("<html>REGISTRO<br>DE USUARIOS</html>");
        btnregistrodeusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistrodeusuarioMouseClicked(evt);
            }
        });
        jpaneladmin.add(btnregistrodeusuario);
        btnregistrodeusuario.setBounds(0, 60, 190, 60);

        btnreportes.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnreportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/documento.png"))); // NOI18N
        btnreportes.setText("REPORTES");
        btnreportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnreportesMouseClicked(evt);
            }
        });
        jpaneladmin.add(btnreportes);
        btnreportes.setBounds(0, 130, 170, 50);

        btnajustes.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnajustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuercas.png"))); // NOI18N
        btnajustes.setText("AJUSTES");
        btnajustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnajustesMouseClicked(evt);
            }
        });
        jpaneladmin.add(btnajustes);
        btnajustes.setBounds(0, 180, 170, 50);

        jpanelgeneral.add(jpaneladmin);
        jpaneladmin.setBounds(0, 220, 190, 250);

        btninicio.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btninicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        btninicio.setText("INICIO");
        btninicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btninicioMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btninicio);
        btninicio.setBounds(0, 0, 140, 50);

        btnAlmacen.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caja.png"))); // NOI18N
        btnAlmacen.setText("ALMACEN");
        btnAlmacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlmacenMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btnAlmacen);
        btnAlmacen.setBounds(0, 50, 160, 50);

        btnregistrodecompras.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnregistrodecompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/camion.png"))); // NOI18N
        btnregistrodecompras.setText("<html>REGISTRO<br>DE COMPRAS</html>");
        btnregistrodecompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistrodecomprasMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btnregistrodecompras);
        btnregistrodecompras.setBounds(0, 100, 170, 50);

        btnregistrodeventas.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnregistrodeventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tienda.png"))); // NOI18N
        btnregistrodeventas.setText("<html>REGISTRO<br>DE VENTAS</html>");
        btnregistrodeventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistrodeventasMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btnregistrodeventas);
        btnregistrodeventas.setBounds(0, 160, 170, 50);

        btncerrarsesion.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btncerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/puerta.png"))); // NOI18N
        btncerrarsesion.setText("<html>CERRAR<br>SESION</html>");
        btncerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncerrarsesionMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btncerrarsesion);
        btncerrarsesion.setBounds(10, 470, 130, 50);

        getContentPane().add(jpanelgeneral);
        jpanelgeneral.setBounds(0, 80, 190, 530);

        jpanelsuperior.setBackground(new java.awt.Color(0, 153, 153));
        jpanelsuperior.setLayout(null);

        lblinventario.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        lblinventario.setText("INVENTARIO");
        jpanelsuperior.add(lblinventario);
        lblinventario.setBounds(20, 20, 180, 30);

        lblimagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carretilla.png"))); // NOI18N
        jpanelsuperior.add(lblimagen1);
        lblimagen1.setBounds(190, 10, 70, 60);

        lblimagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuariovl2.png"))); // NOI18N
        jpanelsuperior.add(lblimagen2);
        lblimagen2.setBounds(810, 20, 50, 40);

        lblRUC.setFont(new java.awt.Font("Cartoon Fun", 0, 14)); // NOI18N
        lblRUC.setText("Agro Integral Perú");
        jpanelsuperior.add(lblRUC);
        lblRUC.setBounds(610, 10, 200, 24);

        lblRol.setText("Empleado");
        jpanelsuperior.add(lblRol);
        lblRol.setBounds(650, 40, 150, 16);

        getContentPane().add(jpanelsuperior);
        jpanelsuperior.setBounds(0, 0, 880, 80);

        tpnMostrar.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        pnl1Inicio.setLayout(null);

        lblSubTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblSubTitulo.setText("RESUMEN DEL DÍA");
        pnl1Inicio.add(lblSubTitulo);
        lblSubTitulo.setBounds(30, 20, 160, 40);

        pnlProductos.setBackground(new java.awt.Color(216, 196, 244));
        pnlProductos.setLayout(null);

        lblProductos.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblProductos.setText("PRODUCTOS");
        pnlProductos.add(lblProductos);
        lblProductos.setBounds(60, 50, 75, 30);
        pnlProductos.add(txtProductos);
        txtProductos.setBounds(20, 20, 150, 30);

        pnl1Inicio.add(pnlProductos);
        pnlProductos.setBounds(370, 360, 190, 90);

        pnlGancias.setBackground(new java.awt.Color(255, 212, 4));
        pnlGancias.setLayout(null);

        lblGanancias.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblGanancias.setText("GANANCIAS");
        pnlGancias.add(lblGanancias);
        lblGanancias.setBounds(60, 50, 80, 30);
        pnlGancias.add(txtGanancias);
        txtGanancias.setBounds(20, 20, 150, 30);

        pnl1Inicio.add(pnlGancias);
        pnlGancias.setBounds(100, 100, 190, 90);

        pnlProveedores.setBackground(new java.awt.Color(199, 180, 159));
        pnlProveedores.setLayout(null);

        lblProveedores.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblProveedores.setText("PROVEEDORES");
        pnlProveedores.add(lblProveedores);
        lblProveedores.setBounds(50, 50, 110, 30);
        pnlProveedores.add(txtProveedores);
        txtProveedores.setBounds(20, 20, 150, 30);

        pnl1Inicio.add(pnlProveedores);
        pnlProveedores.setBounds(370, 100, 190, 90);

        pnlCompraDelMes.setBackground(new java.awt.Color(248, 197, 200));
        pnlCompraDelMes.setLayout(null);

        lblCompraDelMes.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblCompraDelMes.setText("COMPRA DEL MES");
        pnlCompraDelMes.add(lblCompraDelMes);
        lblCompraDelMes.setBounds(40, 50, 120, 30);
        pnlCompraDelMes.add(txtComprasDelMes);
        txtComprasDelMes.setBounds(20, 20, 150, 30);

        pnl1Inicio.add(pnlCompraDelMes);
        pnlCompraDelMes.setBounds(100, 230, 190, 90);

        pnlVentasDelDia.setBackground(new java.awt.Color(160, 204, 92));
        pnlVentasDelDia.setLayout(null);

        lblVentasDelDia.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblVentasDelDia.setText("VENTAS DEL DIA");
        pnlVentasDelDia.add(lblVentasDelDia);
        lblVentasDelDia.setBounds(40, 50, 110, 30);
        pnlVentasDelDia.add(txtVentasDelDia);
        txtVentasDelDia.setBounds(20, 20, 150, 30);

        pnl1Inicio.add(pnlVentasDelDia);
        pnlVentasDelDia.setBounds(370, 230, 190, 90);

        pnlCientes.setBackground(new java.awt.Color(152, 180, 204));
        pnlCientes.setLayout(null);

        lblClientes.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblClientes.setText("CLIENTES");
        pnlCientes.add(lblClientes);
        lblClientes.setBounds(60, 50, 90, 30);
        pnlCientes.add(txtClientes);
        txtClientes.setBounds(20, 20, 150, 30);

        pnl1Inicio.add(pnlCientes);
        pnlCientes.setBounds(100, 360, 190, 90);

        tpnMostrar.addTab("pnl1Inicio", pnl1Inicio);

        pnlRegUsuMostrar.setLayout(null);

        btnCrearUsuario.setBackground(new java.awt.Color(202, 244, 250));
        btnCrearUsuario.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btnCrearUsuario.setText("Crear Usuario");
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });
        pnlRegUsuMostrar.add(btnCrearUsuario);
        btnCrearUsuario.setBounds(230, 60, 210, 40);

        btnEliminar.setBackground(new java.awt.Color(202, 244, 250));
        btnEliminar.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlRegUsuMostrar.add(btnEliminar);
        btnEliminar.setBounds(60, 420, 230, 40);

        tblRegistroUsuarios.setBackground(new java.awt.Color(220, 235, 245));
        tblRegistroUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Usuario ID", "Empleado", "Usuario", "Contraseña", "Tipo", "Telefono", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRegistroUsuarios.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblRegistroUsuarios);

        pnlRegUsuMostrar.add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 660, 240);

        btnEditar.setBackground(new java.awt.Color(226, 237, 241));
        btnEditar.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });
        pnlRegUsuMostrar.add(btnEditar);
        btnEditar.setBounds(370, 420, 230, 40);

        tpnMostrar.addTab("pnlRegUsuMostrar", pnlRegUsuMostrar);

        pnlRegUsuIngresar.setLayout(null);

        lblAgregaryCrearUsuario.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblAgregaryCrearUsuario.setText("AGREGAR Y CREAR USUARIO");
        pnlRegUsuIngresar.add(lblAgregaryCrearUsuario);
        lblAgregaryCrearUsuario.setBounds(50, 50, 220, 30);

        lblSubTitulo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubTitulo1.setText("• Creación de Usuario");
        pnlRegUsuIngresar.add(lblSubTitulo1);
        lblSubTitulo1.setBounds(70, 110, 150, 20);

        lblNombres.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblNombres.setText("Nombres:");
        pnlRegUsuIngresar.add(lblNombres);
        lblNombres.setBounds(70, 160, 60, 30);

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        pnlRegUsuIngresar.add(txtNombres);
        txtNombres.setBounds(130, 160, 190, 30);

        lblApellidos.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblApellidos.setText("Apellidos:");
        pnlRegUsuIngresar.add(lblApellidos);
        lblApellidos.setBounds(330, 160, 60, 30);
        pnlRegUsuIngresar.add(txtApellidos);
        txtApellidos.setBounds(390, 160, 190, 30);

        lblTelefono.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblTelefono.setText("Telefono:");
        pnlRegUsuIngresar.add(lblTelefono);
        lblTelefono.setBounds(70, 230, 60, 30);
        pnlRegUsuIngresar.add(txtTelefono);
        txtTelefono.setBounds(130, 230, 190, 30);

        lblDNIUsuario.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblDNIUsuario.setText("DNI/Usuario:");
        pnlRegUsuIngresar.add(lblDNIUsuario);
        lblDNIUsuario.setBounds(330, 230, 90, 30);
        pnlRegUsuIngresar.add(txtDNIUsuario);
        txtDNIUsuario.setBounds(420, 230, 180, 30);

        lblContraseña.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblContraseña.setText("Contraseña:");
        pnlRegUsuIngresar.add(lblContraseña);
        lblContraseña.setBounds(70, 300, 70, 30);
        pnlRegUsuIngresar.add(txtContraseña);
        txtContraseña.setBounds(140, 300, 180, 30);

        lblTipoUsuario.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblTipoUsuario.setText("Tipo Usuario:");
        pnlRegUsuIngresar.add(lblTipoUsuario);
        lblTipoUsuario.setBounds(330, 300, 80, 30);

        cbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "empleado" }));
        pnlRegUsuIngresar.add(cbTipoUsuario);
        cbTipoUsuario.setBounds(410, 300, 170, 30);

        btnGuardaryAgregarDatos.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btnGuardaryAgregarDatos.setText("Guardar y Agregar Datos");
        btnGuardaryAgregarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardaryAgregarDatosActionPerformed(evt);
            }
        });
        pnlRegUsuIngresar.add(btnGuardaryAgregarDatos);
        btnGuardaryAgregarDatos.setBounds(320, 390, 300, 50);

        rbtActivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbtActivo.setForeground(new java.awt.Color(102, 153, 0));
        rbtActivo.setSelected(true);
        rbtActivo.setText("ACTIVO");
        rbtActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtActivoActionPerformed(evt);
            }
        });
        pnlRegUsuIngresar.add(rbtActivo);
        rbtActivo.setBounds(140, 390, 100, 20);

        rbtInactivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbtInactivo.setForeground(new java.awt.Color(204, 0, 0));
        rbtInactivo.setText("INACTIVO");
        rbtInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtInactivoActionPerformed(evt);
            }
        });
        pnlRegUsuIngresar.add(rbtInactivo);
        rbtInactivo.setBounds(140, 420, 100, 20);

        tpnMostrar.addTab("pnlRegUsuIngresar", pnlRegUsuIngresar);

        pnl1Almacen.setBackground(new java.awt.Color(216, 252, 156));
        pnl1Almacen.setLayout(null);

        lblSubtema2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblSubtema2.setText("REGISTRO DE PRODUCTOS");
        pnl1Almacen.add(lblSubtema2);
        lblSubtema2.setBounds(40, 40, 230, 20);

        cbTipoStock.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        cbTipoStock.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "• Sin Filtro", "• Sin Stock", "• Con stock" }));
        pnl1Almacen.add(cbTipoStock);
        cbTipoStock.setBounds(360, 230, 170, 30);

        tblRegistroProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo de documento", "Producto", "Precio Compra", "Cantidad", "Stock"
            }
        ));
        jScrollPane2.setViewportView(tblRegistroProductos);

        pnl1Almacen.add(jScrollPane2);
        jScrollPane2.setBounds(30, 300, 630, 190);

        lblPreciodeProducto.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lblPreciodeProducto.setText("Precio de compra:");
        pnl1Almacen.add(lblPreciodeProducto);
        lblPreciodeProducto.setBounds(40, 170, 150, 20);

        lblProducto.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lblProducto.setText("Producto: ");
        pnl1Almacen.add(lblProducto);
        lblProducto.setBounds(40, 90, 90, 20);

        lblCantidaddeProducto.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lblCantidaddeProducto.setText("Cantidad de productos: ");
        pnl1Almacen.add(lblCantidaddeProducto);
        lblCantidaddeProducto.setBounds(40, 130, 210, 20);

        btnBuscarAlmacen.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnBuscarAlmacen.setText("Buscar");
        btnBuscarAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlmacenActionPerformed(evt);
            }
        });
        pnl1Almacen.add(btnBuscarAlmacen);
        btnBuscarAlmacen.setBounds(240, 210, 100, 30);
        pnl1Almacen.add(txtBuscar);
        txtBuscar.setBounds(70, 210, 160, 30);

        btnAgregarAlmacen.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnAgregarAlmacen.setText("Agregar");
        btnAgregarAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlmacenActionPerformed(evt);
            }
        });
        pnl1Almacen.add(btnAgregarAlmacen);
        btnAgregarAlmacen.setBounds(510, 40, 120, 40);

        btnEliminarAlmacen.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnEliminarAlmacen.setText("Eliminar");
        btnEliminarAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlmacenActionPerformed(evt);
            }
        });
        pnl1Almacen.add(btnEliminarAlmacen);
        btnEliminarAlmacen.setBounds(510, 100, 120, 40);

        btnEditarAlmacen.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnEditarAlmacen.setText("Editar");
        btnEditarAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAlmacenActionPerformed(evt);
            }
        });
        pnl1Almacen.add(btnEditarAlmacen);
        btnEditarAlmacen.setBounds(510, 160, 120, 40);
        pnl1Almacen.add(txtPreciodeCompra);
        txtPreciodeCompra.setBounds(200, 160, 160, 30);
        pnl1Almacen.add(txtProducto);
        txtProducto.setBounds(130, 80, 160, 30);
        pnl1Almacen.add(txtCantidaddeProducto);
        txtCantidaddeProducto.setBounds(250, 120, 160, 30);

        btnFiltrarAlmacen.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnFiltrarAlmacen.setText("Filtrar");
        btnFiltrarAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarAlmacenActionPerformed(evt);
            }
        });
        pnl1Almacen.add(btnFiltrarAlmacen);
        btnFiltrarAlmacen.setBounds(540, 230, 100, 30);

        lblImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lupa.png"))); // NOI18N
        pnl1Almacen.add(lblImagen1);
        lblImagen1.setBounds(40, 210, 30, 30);

        tpnMostrar.addTab("pnl1Almacen", pnl1Almacen);

        getContentPane().add(tpnMostrar);
        tpnMostrar.setBounds(190, 80, 690, 560);

        setSize(new java.awt.Dimension(894, 644));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btninicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninicioMouseClicked
        tpnMostrar.setSelectedIndex(0);
    }//GEN-LAST:event_btninicioMouseClicked

    private void btnAlmacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlmacenMouseClicked
        actualizarTBLRegistroProductos();
        tpnMostrar.setSelectedIndex(3);
    }//GEN-LAST:event_btnAlmacenMouseClicked

    private void btnregistrodecomprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrodecomprasMouseClicked

    }//GEN-LAST:event_btnregistrodecomprasMouseClicked

    private void btnregistrodeventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrodeventasMouseClicked

    }//GEN-LAST:event_btnregistrodeventasMouseClicked

    private void btncajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncajaMouseClicked

    }//GEN-LAST:event_btncajaMouseClicked

    private void btnregistrodeusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrodeusuarioMouseClicked
        actualizarTBLRegistroUsuarios();
        tpnMostrar.setSelectedIndex(1);
    }//GEN-LAST:event_btnregistrodeusuarioMouseClicked

    private void btnreportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreportesMouseClicked

    }//GEN-LAST:event_btnreportesMouseClicked

    private void btnajustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajustesMouseClicked

    }//GEN-LAST:event_btnajustesMouseClicked

    private void btncerrarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarsesionMouseClicked
        if (JOptionPane.showConfirmDialog(this, "¿Esta seguro de cerrar sesion?", "Lo extrañaremos ;)", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
            baseDeDatos.cerrarConexion();
            FrmLogin login = new FrmLogin();
            login.setVisible(true);
        }
    }//GEN-LAST:event_btncerrarsesionMouseClicked

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        // TODO add your handling code here:
        tpnMostrar.setSelectedIndex(2);
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    private boolean faltanDatosEnTxt(JTextField[] verificame) {
        for (JTextField txt : verificame) {
            if (txt.getText().isBlank()) {
                return true;
            }
        }
        return false;
    }

    private boolean faltanDatosEnTxt(String[] verificame) {
        for (String txt : verificame) {
            if (txt.isBlank()) {
                return true;
            }
        }
        return false;
    }

    private void btnGuardaryAgregarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardaryAgregarDatosActionPerformed
        String errorMensaje = "";
        boolean noIngresar = false;
        if (faltanDatosEnTxt(new JTextField[]{txtNombres, txtApellidos, txtTelefono, txtDNIUsuario, txtContraseña})) {
            errorMensaje += "Error: Falta llenar datos";
            noIngresar = true;
        }

        if (Usuario.muyLargo(txtNombres.getText()) || Usuario.muyLargo(txtApellidos.getText()) || Usuario.muyLargo(txtContraseña.getText())) {
            errorMensaje += "Error: nombres o apellidos o contraseña muy largos.\n";
            noIngresar = true;
        }

        Integer telefono = Usuario.tryParseTelefono(txtTelefono.getText());
        Long usuarioDNI = Usuario.tryParseUsuarioDNI(txtDNIUsuario.getText());
        if (telefono == null) {
            errorMensaje += "Error: Formato de telefono no valido. Debe ser de 6 o 9 digitos\n";
            noIngresar = true;
        }
        if (usuarioDNI == null) {
            errorMensaje += "Error: Formato de DNI no valido.\n";
            noIngresar = true;
        }
        if (noIngresar) {
            JOptionPane.showMessageDialog(this, errorMensaje);
            return;
        }

        boolean esCuentaInactiva = rbtInactivo.isSelected();
        baseDeDatos.crearCuentaUsuario(usuarioDNI, txtNombres.getText(), txtApellidos.getText(), Integer.parseInt(txtTelefono.getText()), txtContraseña.getText(), cbTipoUsuario.getSelectedItem().toString(), esCuentaInactiva);
        actualizarTBLRegistroUsuarios();
    }//GEN-LAST:event_btnGuardaryAgregarDatosActionPerformed

    private void rbtActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtActivoActionPerformed
        rbtActivo.setSelected(true);
        rbtInactivo.setSelected(false);

    }//GEN-LAST:event_rbtActivoActionPerformed

    private void rbtInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtInactivoActionPerformed
        rbtInactivo.setSelected(true);
        rbtActivo.setSelected(false);

    }//GEN-LAST:event_rbtInactivoActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(this, "¿Esta seguro de salir? Su sesion se cerrará automaticamente.", "Lo extrañaremos ;)", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            baseDeDatos.cerrarConexion();
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private String[] separarNombresApellidos(String nombresApellidos) {
        int tamaño = nombresApellidos.length();
        String[] nombre_apellido = new String[]{"", ""};
        int j = 0;
        for (int i = 0; i < tamaño; i++) {
            if (nombresApellidos.charAt(i) == ' ' && j < nombre_apellido.length - 1) {
                j++;
                continue;
            }
            nombre_apellido[j] += nombresApellidos.charAt(i);
        }
        return nombre_apellido;
    }

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccion = tblRegistroUsuarios.getSelectedRow();
        if (filaSeleccion < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila para eliminar");
            return;
        }
        int usuario_id = Integer.parseInt(listaModelos[indiceRegUsu].getValueAt(filaSeleccion, 0).toString());
        baseDeDatos.eliminarUsuario(usuario_id);
        actualizarTBLRegistroUsuarios();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        int filaSeleccion = tblRegistroUsuarios.getSelectedRow();
        if (filaSeleccion < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila para editar");
            return;
        }

        if (tieneCeldasVacias(listaModelos[indiceRegUsu], filaSeleccion)) {
            JOptionPane.showMessageDialog(this, "Faltan datos en la fila");
            return;
        }

        int usuID = Integer.parseInt(listaModelos[indiceRegUsu].getValueAt(filaSeleccion, 0).toString());
        //Empleado nombre String
        String[] nombres_apellidos = separarNombresApellidos(listaModelos[indiceRegUsu].getValueAt(filaSeleccion, 1).toString());
        String nombre = nombres_apellidos[0];
        String apellido = nombres_apellidos[1];
        //UsuarioDNIoRUC Long
        long usuarioDNI = Long.parseLong(listaModelos[indiceRegUsu].getValueAt(filaSeleccion, 2).toString());
        //Contraseña String
        String contra = listaModelos[indiceRegUsu].getValueAt(filaSeleccion, 3).toString();
        //Tipo String
        String rol = listaModelos[indiceRegUsu].getValueAt(filaSeleccion, 4).toString();
        //Telefono int
        int fono = Integer.parseInt(listaModelos[indiceRegUsu].getValueAt(filaSeleccion, 5).toString());

        //Estado boolean
        boolean esCuentaBloqueada = Usuario.parseEsCuentaBloqueada(listaModelos[indiceRegUsu].getValueAt(filaSeleccion, 6).toString());
        //long usuarioDNI, String contraseña, String rol, LocalDate fechaUltimoCambio,int intentosFallidos, boolean cuentaBloqueada, String nombres, String apellidos, int telefono, int usuario_id
        baseDeDatos.actualizarUsuario(usuarioDNI, contra, rol, LocalDate.now(), 0, esCuentaBloqueada, nombre, apellido, fono, usuID);
        actualizarTBLRegistroUsuarios();

    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnAgregarAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlmacenActionPerformed
        String errorMensaje = "";
        boolean noRegistrar = false;
        if (faltanDatosEnTxt(new JTextField[]{txtProducto, txtCantidaddeProducto, txtPreciodeCompra})) {
            JOptionPane.showMessageDialog(this, "Faltan ingresar datos de producto");
            return;
        }
        Integer cantidadProducto = Producto.tryParseCantidad(txtCantidaddeProducto.getText());
        Double precioCompra = Producto.tryParsePrecioCompra(txtPreciodeCompra.getText());
        String producto = txtProducto.getText();
        if (cantidadProducto == null) {
            errorMensaje += "Formato de cantidad incorrecto. Debe ingresar un número natural.\n";
            noRegistrar = true;
        }
        if (precioCompra == null) {
            errorMensaje += "Formato de precio incorrecto. Debe ingresar un número real.\n";
            noRegistrar = true;
        }
        if (noRegistrar) {
            JOptionPane.showMessageDialog(this, errorMensaje);
            return;
        }
        //                  (String tipoDoc,String producto,double precio,int cantidad,String stock) {
        baseDeDatos.crearProducto("Sin documento", producto, precioCompra, cantidadProducto, Producto.calcularStock(cantidadProducto));
        actualizarTBLRegistroProductos();
    }//GEN-LAST:event_btnAgregarAlmacenActionPerformed

    private void btnEliminarAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlmacenActionPerformed
        int filaSeleccion = tblRegistroProductos.getSelectedRow();
        if (filaSeleccion < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila para eliminar");
            return;
        }
        int producto_id = Integer.parseInt(listaModelos[indiceRegProd].getValueAt(filaSeleccion, 0).toString());
        baseDeDatos.eliminarProducto(producto_id);
        actualizarTBLRegistroProductos();
    }//GEN-LAST:event_btnEliminarAlmacenActionPerformed

    private boolean tieneCeldasVacias(DefaultTableModel modelo, int fila) {
        for (int i = 0; i < modelo.getColumnCount(); i++) {
            if (modelo.getValueAt(fila, i).toString().isBlank()) {
                return true;
            }
        }
        return false;
    }

    private void btnEditarAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAlmacenActionPerformed
        int filaSeleccion = tblRegistroProductos.getSelectedRow();
        if (filaSeleccion < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila para editar");
            return;
        }

        //Revisar no espacios en blanco
        if (tieneCeldasVacias(listaModelos[indiceRegProd], filaSeleccion)) {
            JOptionPane.showMessageDialog(this, "Faltan datos en la fila");
            return;
        }

        //formato correcto
        String errorMensaje = "";
        boolean noEntrar = false;
        Integer producto_id = Integer.parseInt(listaModelos[indiceRegProd].getValueAt(filaSeleccion, 0).toString());
        String tipoDoc = listaModelos[indiceRegProd].getValueAt(filaSeleccion, 1).toString();
        String producto = listaModelos[indiceRegProd].getValueAt(filaSeleccion, 2).toString();
        Double precio = Double.parseDouble(listaModelos[indiceRegProd].getValueAt(filaSeleccion, 3).toString());
        if (precio == null) {
            errorMensaje += "Formato de precio incorrecto. Ingrese un numero real.\n";
            noEntrar = true;
        }

        Integer cantidad = Integer.parseInt(listaModelos[indiceRegProd].getValueAt(filaSeleccion, 4).toString());
        if (cantidad == null) {
            errorMensaje += "Formato de precio incorrecto. Ingrese un numero natural.\n";
            noEntrar = true;
        }

        if (noEntrar) {
            JOptionPane.showMessageDialog(this, errorMensaje);
            return;
        }

        String stock = listaModelos[indiceRegProd].getValueAt(filaSeleccion, 5).toString();

        baseDeDatos.actualizarProducto(producto_id, tipoDoc, producto, precio, cantidad, stock);
        actualizarTBLRegistroProductos();
    }//GEN-LAST:event_btnEditarAlmacenActionPerformed

    private void btnFiltrarAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarAlmacenActionPerformed
        actualizarTBLRegistroProductos();
    }//GEN-LAST:event_btnFiltrarAlmacenActionPerformed

    
    private static boolean coincideAlgo(String clave, String palabra){
        int numCoinc;
        for (int i = 0; i <= (palabra.length()-clave.length()); i++) {
            numCoinc=0;
            for (int j = 0; j < clave.length(); j++) {
                if(palabra.charAt(i+j)==clave.charAt(j)){
                    numCoinc++;
                    continue;
                }
                break;
            }
            if(numCoinc==clave.length()){
                return true;
            }
        }
        return false;
    }
    
    private void btnBuscarAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlmacenActionPerformed
        //revisar que no este en blanco
        
        //hacer el for para buscar y añadir a una lista
        
        //mostrar la lista en la tabla
    }//GEN-LAST:event_btnBuscarAlmacenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuDinamico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAlmacen;
    private javax.swing.JLabel btnAlmacen;
    private javax.swing.JButton btnBuscarAlmacen;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditarAlmacen;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarAlmacen;
    private javax.swing.JButton btnFiltrarAlmacen;
    private javax.swing.JButton btnGuardaryAgregarDatos;
    private javax.swing.JLabel btnajustes;
    private javax.swing.JLabel btncaja;
    private javax.swing.JLabel btncerrarsesion;
    private javax.swing.JLabel btninicio;
    private javax.swing.JLabel btnregistrodecompras;
    private javax.swing.JLabel btnregistrodeusuario;
    private javax.swing.JLabel btnregistrodeventas;
    private javax.swing.JLabel btnreportes;
    private javax.swing.JComboBox<String> cbTipoStock;
    private javax.swing.JComboBox<String> cbTipoUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpaneladmin;
    private javax.swing.JPanel jpanelgeneral;
    private javax.swing.JPanel jpanelsuperior;
    private javax.swing.JLabel lblAgregaryCrearUsuario;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCantidaddeProducto;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblCompraDelMes;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblDNIUsuario;
    private javax.swing.JLabel lblGanancias;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblPreciodeProducto;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblProveedores;
    private javax.swing.JLabel lblRUC;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblSubTitulo1;
    private javax.swing.JLabel lblSubtema2;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JLabel lblVentasDelDia;
    private javax.swing.JLabel lblimagen1;
    private javax.swing.JLabel lblimagen2;
    private javax.swing.JLabel lblinventario;
    private javax.swing.JPanel pnl1Almacen;
    private javax.swing.JPanel pnl1Inicio;
    private javax.swing.JPanel pnlCientes;
    private javax.swing.JPanel pnlCompraDelMes;
    private javax.swing.JPanel pnlGancias;
    private javax.swing.JPanel pnlProductos;
    private javax.swing.JPanel pnlProveedores;
    private javax.swing.JPanel pnlRegUsuIngresar;
    private javax.swing.JPanel pnlRegUsuMostrar;
    private javax.swing.JPanel pnlVentasDelDia;
    private javax.swing.JRadioButton rbtActivo;
    private javax.swing.JRadioButton rbtInactivo;
    private javax.swing.JTable tblRegistroProductos;
    private javax.swing.JTable tblRegistroUsuarios;
    private javax.swing.JTabbedPane tpnMostrar;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidaddeProducto;
    private javax.swing.JTextField txtClientes;
    private javax.swing.JTextField txtComprasDelMes;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtDNIUsuario;
    private javax.swing.JTextField txtGanancias;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPreciodeCompra;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtProductos;
    private javax.swing.JTextField txtProveedores;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtVentasDelDia;
    // End of variables declaration//GEN-END:variables
}
