package MenuDinamico;

import Usuario.Usuario;
import Usuario.Administrador;
import Usuario.Empleado;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class FrmMenuDinamico extends javax.swing.JFrame {

    Usuario usuario;

    /**
     * Creates new form MenuDinamico
     */
    public FrmMenuDinamico() {
        initComponents();
        jpaneladmin.setVisible(false);

    }

    public void modificarSegunRol(Usuario usuario) {
        if (usuario.getRol().equalsIgnoreCase("administrador")) {
            this.usuario = new Administrador(usuario);
            jpaneladmin.setVisible(true);
            jpaneladmin.setEnabled(true);
        } else {
            this.usuario = new Empleado(usuario);
        }
        lblRol.setText(usuario.getRol());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelgeneral = new javax.swing.JPanel();
        jpaneladmin = new javax.swing.JPanel();
        btncaja = new javax.swing.JLabel();
        btnregistrodeusuario = new javax.swing.JLabel();
        btnreportes = new javax.swing.JLabel();
        btnajustes = new javax.swing.JLabel();
        btninicio = new javax.swing.JLabel();
        btnAlmacen = new javax.swing.JLabel();
        btnregistrodecompras = new javax.swing.JLabel();
        btnregistrodeventas = new javax.swing.JLabel();
        btncerrarsesion = new javax.swing.JLabel();
        jpanelsuperior = new javax.swing.JPanel();
        lblinventario = new javax.swing.JLabel();
        lblimagen1 = new javax.swing.JLabel();
        lblimagen2 = new javax.swing.JLabel();
        lblRUC = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        tpnMostrar = new javax.swing.JTabbedPane();
        pnl1Inicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        pnlRegistroUsuAdminMain = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnAgregarUsuario = new javax.swing.JButton();
        btnCrearUsuario = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistroUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jpanelgeneral.setBackground(new java.awt.Color(0, 153, 153));
        jpanelgeneral.setLayout(null);

        jpaneladmin.setBackground(new java.awt.Color(0, 153, 153));
        jpaneladmin.setEnabled(false);
        jpaneladmin.setLayout(null);

        btncaja.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btncaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dinero.png"))); // NOI18N
        btncaja.setText("CAJA");
        btncaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncajaMouseClicked(evt);
            }
        });
        jpaneladmin.add(btncaja);
        btncaja.setBounds(0, 0, 140, 50);

        btnregistrodeusuario.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnregistrodeusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/personas.png"))); // NOI18N
        btnregistrodeusuario.setText("<html>REGISTRO<br>DE USUARIOS</html>");
        btnregistrodeusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistrodeusuarioMouseClicked(evt);
            }
        });
        jpaneladmin.add(btnregistrodeusuario);
        btnregistrodeusuario.setBounds(0, 60, 190, 60);

        btnreportes.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnreportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/documento.png"))); // NOI18N
        btnreportes.setText("REPORTES");
        btnreportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnreportesMouseClicked(evt);
            }
        });
        jpaneladmin.add(btnreportes);
        btnreportes.setBounds(0, 130, 170, 50);

        btnajustes.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnajustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuercas.png"))); // NOI18N
        btnajustes.setText("AJUSTES");
        btnajustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnajustesMouseClicked(evt);
            }
        });
        jpaneladmin.add(btnajustes);
        btnajustes.setBounds(0, 180, 170, 50);

        jpanelgeneral.add(jpaneladmin);
        jpaneladmin.setBounds(0, 220, 190, 250);

        btninicio.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btninicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        btninicio.setText("INICIO");
        btninicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btninicioMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btninicio);
        btninicio.setBounds(0, 0, 140, 50);

        btnAlmacen.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caja.png"))); // NOI18N
        btnAlmacen.setText("ALMACEN");
        btnAlmacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlmacenMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btnAlmacen);
        btnAlmacen.setBounds(0, 50, 160, 50);

        btnregistrodecompras.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnregistrodecompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/camion.png"))); // NOI18N
        btnregistrodecompras.setText("<html>REGISTRO<br>DE COMPRAS</html>");
        btnregistrodecompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistrodecomprasMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btnregistrodecompras);
        btnregistrodecompras.setBounds(0, 100, 170, 50);

        btnregistrodeventas.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnregistrodeventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tienda.png"))); // NOI18N
        btnregistrodeventas.setText("<html>REGISTRO<br>DE VENTAS</html>");
        btnregistrodeventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistrodeventasMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btnregistrodeventas);
        btnregistrodeventas.setBounds(0, 160, 170, 50);

        btncerrarsesion.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btncerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/puerta.png"))); // NOI18N
        btncerrarsesion.setText("SALIR");
        btncerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncerrarsesionMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btncerrarsesion);
        btncerrarsesion.setBounds(10, 470, 130, 50);

        getContentPane().add(jpanelgeneral);
        jpanelgeneral.setBounds(0, 80, 190, 530);

        jpanelsuperior.setBackground(new java.awt.Color(0, 153, 153));
        jpanelsuperior.setLayout(null);

        lblinventario.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        lblinventario.setText("INVENTARIO");
        jpanelsuperior.add(lblinventario);
        lblinventario.setBounds(20, 20, 180, 30);

        lblimagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carretilla.png"))); // NOI18N
        jpanelsuperior.add(lblimagen1);
        lblimagen1.setBounds(190, 10, 70, 60);

        lblimagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuariovl2.png"))); // NOI18N
        jpanelsuperior.add(lblimagen2);
        lblimagen2.setBounds(810, 20, 50, 40);

        lblRUC.setFont(new java.awt.Font("Cartoon Fun", 0, 14)); // NOI18N
        lblRUC.setText("Agro Integral Perú");
        jpanelsuperior.add(lblRUC);
        lblRUC.setBounds(610, 10, 200, 24);

        lblRol.setText("Empleado");
        jpanelsuperior.add(lblRol);
        lblRol.setBounds(650, 40, 150, 16);

        getContentPane().add(jpanelsuperior);
        jpanelsuperior.setBounds(0, 0, 880, 80);

        tpnMostrar.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        pnl1Inicio.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("RESUMEN DEL DÍA");
        pnl1Inicio.add(jLabel1);
        jLabel1.setBounds(30, 20, 160, 40);

        jPanel2.setBackground(new java.awt.Color(216, 196, 244));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setText("PRODUCTOS");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 50, 75, 30);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(20, 20, 150, 30);

        pnl1Inicio.add(jPanel2);
        jPanel2.setBounds(370, 360, 190, 90);

        jPanel3.setBackground(new java.awt.Color(255, 212, 4));
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setText("GANANCIAS");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(60, 50, 80, 30);
        jPanel3.add(jTextField12);
        jTextField12.setBounds(20, 20, 150, 30);

        pnl1Inicio.add(jPanel3);
        jPanel3.setBounds(100, 100, 190, 90);

        jPanel4.setBackground(new java.awt.Color(199, 180, 159));
        jPanel4.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setText("PROVEEDORES");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(50, 50, 110, 30);
        jPanel4.add(jTextField8);
        jTextField8.setBounds(20, 20, 150, 30);

        pnl1Inicio.add(jPanel4);
        jPanel4.setBounds(370, 100, 190, 90);

        jPanel5.setBackground(new java.awt.Color(248, 197, 200));
        jPanel5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel5.setText("COMPRA DEL MES");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(40, 50, 120, 30);
        jPanel5.add(jTextField9);
        jTextField9.setBounds(20, 20, 150, 30);

        pnl1Inicio.add(jPanel5);
        jPanel5.setBounds(100, 230, 190, 90);

        jPanel6.setBackground(new java.awt.Color(160, 204, 92));
        jPanel6.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel6.setText("VENTAS DEL DIA");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(40, 50, 110, 30);
        jPanel6.add(jTextField10);
        jTextField10.setBounds(20, 20, 150, 30);

        pnl1Inicio.add(jPanel6);
        jPanel6.setBounds(370, 230, 190, 90);

        jPanel7.setBackground(new java.awt.Color(152, 180, 204));
        jPanel7.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel7.setText("CLIENTES");
        jPanel7.add(jLabel7);
        jLabel7.setBounds(60, 50, 90, 30);
        jPanel7.add(jTextField11);
        jTextField11.setBounds(20, 20, 150, 30);

        pnl1Inicio.add(jPanel7);
        jPanel7.setBounds(100, 360, 190, 90);

        tpnMostrar.addTab("pnl1Inicio", pnl1Inicio);

        pnlRegistroUsuAdminMain.setLayout(null);

        btnEditar.setBackground(new java.awt.Color(226, 237, 241));
        btnEditar.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btnEditar.setText("Editar");
        pnlRegistroUsuAdminMain.add(btnEditar);
        btnEditar.setBounds(370, 420, 230, 40);

        btnAgregarUsuario.setBackground(new java.awt.Color(226, 237, 241));
        btnAgregarUsuario.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btnAgregarUsuario.setText("Agregar Empleado");
        pnlRegistroUsuAdminMain.add(btnAgregarUsuario);
        btnAgregarUsuario.setBounds(60, 60, 230, 40);

        btnCrearUsuario.setBackground(new java.awt.Color(202, 244, 250));
        btnCrearUsuario.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btnCrearUsuario.setText("Crear Usuario");
        pnlRegistroUsuAdminMain.add(btnCrearUsuario);
        btnCrearUsuario.setBounds(370, 60, 230, 40);

        btnEliminar.setBackground(new java.awt.Color(202, 244, 250));
        btnEliminar.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        pnlRegistroUsuAdminMain.add(btnEliminar);
        btnEliminar.setBounds(60, 420, 230, 40);

        tblRegistroUsuarios.setBackground(new java.awt.Color(220, 235, 245));
        tblRegistroUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Empleado", "Usuario", "Contraseña", "Tipo", "Telefono", "Estado"
            }
        ));
        tblRegistroUsuarios.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblRegistroUsuarios);

        pnlRegistroUsuAdminMain.add(jScrollPane1);
        jScrollPane1.setBounds(30, 140, 630, 230);

        tpnMostrar.addTab("Registro Administrador", pnlRegistroUsuAdminMain);

        getContentPane().add(tpnMostrar);
        tpnMostrar.setBounds(190, 80, 690, 560);

        setSize(new java.awt.Dimension(894, 644));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarNombre(JLabel label) {
        JOptionPane.showMessageDialog(this, "el boton" + label.getText() + " FUNCIONA!!!");
    }

    private void btninicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninicioMouseClicked
        mostrarNombre(btninicio);
        
    }//GEN-LAST:event_btninicioMouseClicked

    private void btnAlmacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlmacenMouseClicked
        mostrarNombre(btnAlmacen);
    }//GEN-LAST:event_btnAlmacenMouseClicked

    private void btnregistrodecomprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrodecomprasMouseClicked
        mostrarNombre(btnAlmacen);
    }//GEN-LAST:event_btnregistrodecomprasMouseClicked

    private void btnregistrodeventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrodeventasMouseClicked
        mostrarNombre(btnregistrodeventas);
    }//GEN-LAST:event_btnregistrodeventasMouseClicked

    private void btncajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncajaMouseClicked
        mostrarNombre(btncaja);
    }//GEN-LAST:event_btncajaMouseClicked

    private void btnregistrodeusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrodeusuarioMouseClicked
        mostrarNombre(btnregistrodeusuario);
    }//GEN-LAST:event_btnregistrodeusuarioMouseClicked

    private void btnreportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreportesMouseClicked
        mostrarNombre(btnreportes);
    }//GEN-LAST:event_btnreportesMouseClicked

    private void btnajustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajustesMouseClicked
        mostrarNombre(btnajustes);
    }//GEN-LAST:event_btnajustesMouseClicked

    private void btncerrarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarsesionMouseClicked
        mostrarNombre(btncerrarsesion);
    }//GEN-LAST:event_btncerrarsesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuDinamico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JLabel btnAlmacen;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel btnajustes;
    private javax.swing.JLabel btncaja;
    private javax.swing.JLabel btncerrarsesion;
    private javax.swing.JLabel btninicio;
    private javax.swing.JLabel btnregistrodecompras;
    private javax.swing.JLabel btnregistrodeusuario;
    private javax.swing.JLabel btnregistrodeventas;
    private javax.swing.JLabel btnreportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel jpaneladmin;
    private javax.swing.JPanel jpanelgeneral;
    private javax.swing.JPanel jpanelsuperior;
    private javax.swing.JLabel lblRUC;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblimagen1;
    private javax.swing.JLabel lblimagen2;
    private javax.swing.JLabel lblinventario;
    private javax.swing.JPanel pnl1Inicio;
    private javax.swing.JPanel pnlRegistroUsuAdminMain;
    private javax.swing.JTable tblRegistroUsuarios;
    private javax.swing.JTabbedPane tpnMostrar;
    // End of variables declaration//GEN-END:variables
}
