package MenuDinamico;

import Usuario.Usuario;
import ServiciosUsuario.ConvertidorUsuario;
import Usuario.Administrador;
import Usuario.Empleado;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import GestorDatosPermanentes.SQLiteManager;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class FrmMenuDinamico extends javax.swing.JFrame {

    Usuario usuario;
    SQLiteManager baseDeDatos;
    DefaultTableModel modelo;

    /**
     * Creates new form MenuDinamico
     */
    public FrmMenuDinamico() {
        initComponents();
        jpaneladmin.setVisible(false);
        baseDeDatos=new SQLiteManager();
        String[] columnas={"Empleado","Usuario","Contraseña","Tipo","Telefono","Estado"};
        modelo= new DefaultTableModel(columnas,0);
        tblRegistroUsuarios.setModel(modelo);
        
    }

    public void modificarSegunRol(Usuario usuario) {
        if (usuario.getRol().equalsIgnoreCase("administrador")) {
            this.usuario = new Administrador(usuario);
            jpaneladmin.setVisible(true);
            jpaneladmin.setEnabled(true);
        } else {
            this.usuario = new Empleado(usuario);
        }
        lblRol.setText(usuario.getRol());
    }
    
    private void actualizarTBLRegistroUsuarios(){
        
        modelo.setRowCount(0);
        ArrayList<Usuario> lista=baseDeDatos.obtenerUsuarios();
        
        for (Usuario usu : lista) {
            //String[] columnas={"Empleado","Usuario","Contraseña","Tipo","Telefono","Estado"};
            Object[] datoFila={usu.getNombres(),usu.getUsuarioDNI(),usu.getContraseña(),usu.getRol(),usu.getTelefono(),ConvertidorUsuario.parseEsCuentaBloqueada(usu.esCuentaBloqueada())};
            modelo.addRow(datoFila);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelgeneral = new javax.swing.JPanel();
        jpaneladmin = new javax.swing.JPanel();
        btncaja = new javax.swing.JLabel();
        btnregistrodeusuario = new javax.swing.JLabel();
        btnreportes = new javax.swing.JLabel();
        btnajustes = new javax.swing.JLabel();
        btninicio = new javax.swing.JLabel();
        btnAlmacen = new javax.swing.JLabel();
        btnregistrodecompras = new javax.swing.JLabel();
        btnregistrodeventas = new javax.swing.JLabel();
        btncerrarsesion = new javax.swing.JLabel();
        jpanelsuperior = new javax.swing.JPanel();
        lblinventario = new javax.swing.JLabel();
        lblimagen1 = new javax.swing.JLabel();
        lblimagen2 = new javax.swing.JLabel();
        lblRUC = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        tpnMostrar = new javax.swing.JTabbedPane();
        pnl1Inicio = new javax.swing.JPanel();
        lblSubTitulo = new javax.swing.JLabel();
        pnlProductos = new javax.swing.JPanel();
        lblProductos = new javax.swing.JLabel();
        txtProductos = new javax.swing.JTextField();
        pnlGancias = new javax.swing.JPanel();
        lblGanancias = new javax.swing.JLabel();
        txtGanancias = new javax.swing.JTextField();
        pnlProveedores = new javax.swing.JPanel();
        lblProveedores = new javax.swing.JLabel();
        txtProveedores = new javax.swing.JTextField();
        pnlCompraDelMes = new javax.swing.JPanel();
        lblCompraDelMes = new javax.swing.JLabel();
        txtComprasDelMes = new javax.swing.JTextField();
        pnlVentasDelDia = new javax.swing.JPanel();
        lblVentasDelDia = new javax.swing.JLabel();
        txtVentasDelDia = new javax.swing.JTextField();
        pnlCientes = new javax.swing.JPanel();
        lblClientes = new javax.swing.JLabel();
        txtClientes = new javax.swing.JTextField();
        pnlRegistroUsuAdminMain = new javax.swing.JPanel();
        btnCrearUsuario = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistroUsuarios = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        pnlRegistroUsuAdminMain1 = new javax.swing.JPanel();
        lblAgregaryCrearUsuario = new javax.swing.JLabel();
        lblSubTitulo1 = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblDNIUsuario = new javax.swing.JLabel();
        txtDNIUsuario = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        lblTipoUsuario = new javax.swing.JLabel();
        cbTipoUsuario = new javax.swing.JComboBox<>();
        btnGuardaryAgregarDatos = new javax.swing.JButton();
        rbtActivo = new javax.swing.JRadioButton();
        rbtInactivo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jpanelgeneral.setBackground(new java.awt.Color(0, 153, 153));
        jpanelgeneral.setLayout(null);

        jpaneladmin.setBackground(new java.awt.Color(0, 153, 153));
        jpaneladmin.setEnabled(false);
        jpaneladmin.setLayout(null);

        btncaja.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btncaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dinero.png"))); // NOI18N
        btncaja.setText("CAJA");
        btncaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncajaMouseClicked(evt);
            }
        });
        jpaneladmin.add(btncaja);
        btncaja.setBounds(0, 0, 140, 50);

        btnregistrodeusuario.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnregistrodeusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/personas.png"))); // NOI18N
        btnregistrodeusuario.setText("<html>REGISTRO<br>DE USUARIOS</html>");
        btnregistrodeusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistrodeusuarioMouseClicked(evt);
            }
        });
        jpaneladmin.add(btnregistrodeusuario);
        btnregistrodeusuario.setBounds(0, 60, 190, 60);

        btnreportes.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnreportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/documento.png"))); // NOI18N
        btnreportes.setText("REPORTES");
        btnreportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnreportesMouseClicked(evt);
            }
        });
        jpaneladmin.add(btnreportes);
        btnreportes.setBounds(0, 130, 170, 50);

        btnajustes.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnajustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuercas.png"))); // NOI18N
        btnajustes.setText("AJUSTES");
        btnajustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnajustesMouseClicked(evt);
            }
        });
        jpaneladmin.add(btnajustes);
        btnajustes.setBounds(0, 180, 170, 50);

        jpanelgeneral.add(jpaneladmin);
        jpaneladmin.setBounds(0, 220, 190, 250);

        btninicio.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btninicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        btninicio.setText("INICIO");
        btninicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btninicioMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btninicio);
        btninicio.setBounds(0, 0, 140, 50);

        btnAlmacen.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caja.png"))); // NOI18N
        btnAlmacen.setText("ALMACEN");
        btnAlmacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlmacenMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btnAlmacen);
        btnAlmacen.setBounds(0, 50, 160, 50);

        btnregistrodecompras.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnregistrodecompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/camion.png"))); // NOI18N
        btnregistrodecompras.setText("<html>REGISTRO<br>DE COMPRAS</html>");
        btnregistrodecompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistrodecomprasMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btnregistrodecompras);
        btnregistrodecompras.setBounds(0, 100, 170, 50);

        btnregistrodeventas.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btnregistrodeventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tienda.png"))); // NOI18N
        btnregistrodeventas.setText("<html>REGISTRO<br>DE VENTAS</html>");
        btnregistrodeventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistrodeventasMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btnregistrodeventas);
        btnregistrodeventas.setBounds(0, 160, 170, 50);

        btncerrarsesion.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btncerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/puerta.png"))); // NOI18N
        btncerrarsesion.setText("SALIR");
        btncerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncerrarsesionMouseClicked(evt);
            }
        });
        jpanelgeneral.add(btncerrarsesion);
        btncerrarsesion.setBounds(10, 470, 130, 50);

        getContentPane().add(jpanelgeneral);
        jpanelgeneral.setBounds(0, 80, 190, 530);

        jpanelsuperior.setBackground(new java.awt.Color(0, 153, 153));
        jpanelsuperior.setLayout(null);

        lblinventario.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        lblinventario.setText("INVENTARIO");
        jpanelsuperior.add(lblinventario);
        lblinventario.setBounds(20, 20, 180, 30);

        lblimagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carretilla.png"))); // NOI18N
        jpanelsuperior.add(lblimagen1);
        lblimagen1.setBounds(190, 10, 70, 60);

        lblimagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuariovl2.png"))); // NOI18N
        jpanelsuperior.add(lblimagen2);
        lblimagen2.setBounds(810, 20, 50, 40);

        lblRUC.setFont(new java.awt.Font("Cartoon Fun", 0, 14)); // NOI18N
        lblRUC.setText("Agro Integral Perú");
        jpanelsuperior.add(lblRUC);
        lblRUC.setBounds(610, 10, 200, 19);

        lblRol.setText("Empleado");
        jpanelsuperior.add(lblRol);
        lblRol.setBounds(650, 40, 150, 16);

        getContentPane().add(jpanelsuperior);
        jpanelsuperior.setBounds(0, 0, 880, 80);

        tpnMostrar.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        pnl1Inicio.setLayout(null);

        lblSubTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblSubTitulo.setText("RESUMEN DEL DÍA");
        pnl1Inicio.add(lblSubTitulo);
        lblSubTitulo.setBounds(30, 20, 160, 40);

        pnlProductos.setBackground(new java.awt.Color(216, 196, 244));
        pnlProductos.setLayout(null);

        lblProductos.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblProductos.setText("PRODUCTOS");
        pnlProductos.add(lblProductos);
        lblProductos.setBounds(60, 50, 75, 30);
        pnlProductos.add(txtProductos);
        txtProductos.setBounds(20, 20, 150, 30);

        pnl1Inicio.add(pnlProductos);
        pnlProductos.setBounds(370, 360, 190, 90);

        pnlGancias.setBackground(new java.awt.Color(255, 212, 4));
        pnlGancias.setLayout(null);

        lblGanancias.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblGanancias.setText("GANANCIAS");
        pnlGancias.add(lblGanancias);
        lblGanancias.setBounds(60, 50, 80, 30);
        pnlGancias.add(txtGanancias);
        txtGanancias.setBounds(20, 20, 150, 30);

        pnl1Inicio.add(pnlGancias);
        pnlGancias.setBounds(100, 100, 190, 90);

        pnlProveedores.setBackground(new java.awt.Color(199, 180, 159));
        pnlProveedores.setLayout(null);

        lblProveedores.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblProveedores.setText("PROVEEDORES");
        pnlProveedores.add(lblProveedores);
        lblProveedores.setBounds(50, 50, 110, 30);
        pnlProveedores.add(txtProveedores);
        txtProveedores.setBounds(20, 20, 150, 30);

        pnl1Inicio.add(pnlProveedores);
        pnlProveedores.setBounds(370, 100, 190, 90);

        pnlCompraDelMes.setBackground(new java.awt.Color(248, 197, 200));
        pnlCompraDelMes.setLayout(null);

        lblCompraDelMes.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblCompraDelMes.setText("COMPRA DEL MES");
        pnlCompraDelMes.add(lblCompraDelMes);
        lblCompraDelMes.setBounds(40, 50, 120, 30);
        pnlCompraDelMes.add(txtComprasDelMes);
        txtComprasDelMes.setBounds(20, 20, 150, 30);

        pnl1Inicio.add(pnlCompraDelMes);
        pnlCompraDelMes.setBounds(100, 230, 190, 90);

        pnlVentasDelDia.setBackground(new java.awt.Color(160, 204, 92));
        pnlVentasDelDia.setLayout(null);

        lblVentasDelDia.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblVentasDelDia.setText("VENTAS DEL DIA");
        pnlVentasDelDia.add(lblVentasDelDia);
        lblVentasDelDia.setBounds(40, 50, 110, 30);
        pnlVentasDelDia.add(txtVentasDelDia);
        txtVentasDelDia.setBounds(20, 20, 150, 30);

        pnl1Inicio.add(pnlVentasDelDia);
        pnlVentasDelDia.setBounds(370, 230, 190, 90);

        pnlCientes.setBackground(new java.awt.Color(152, 180, 204));
        pnlCientes.setLayout(null);

        lblClientes.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblClientes.setText("CLIENTES");
        pnlCientes.add(lblClientes);
        lblClientes.setBounds(60, 50, 90, 30);
        pnlCientes.add(txtClientes);
        txtClientes.setBounds(20, 20, 150, 30);

        pnl1Inicio.add(pnlCientes);
        pnlCientes.setBounds(100, 360, 190, 90);

        tpnMostrar.addTab("pnl1Inicio", pnl1Inicio);

        pnlRegistroUsuAdminMain.setLayout(null);

        btnCrearUsuario.setBackground(new java.awt.Color(202, 244, 250));
        btnCrearUsuario.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btnCrearUsuario.setText("Crear Usuario");
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });
        pnlRegistroUsuAdminMain.add(btnCrearUsuario);
        btnCrearUsuario.setBounds(230, 60, 210, 40);

        btnEliminar.setBackground(new java.awt.Color(202, 244, 250));
        btnEliminar.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        pnlRegistroUsuAdminMain.add(btnEliminar);
        btnEliminar.setBounds(60, 420, 230, 40);

        tblRegistroUsuarios.setBackground(new java.awt.Color(220, 235, 245));
        tblRegistroUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Empleado", "Usuario", "Contraseña", "Tipo", "Telefono", "Estado"
            }
        ));
        tblRegistroUsuarios.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblRegistroUsuarios);

        pnlRegistroUsuAdminMain.add(jScrollPane1);
        jScrollPane1.setBounds(30, 140, 630, 230);

        btnEditar.setBackground(new java.awt.Color(226, 237, 241));
        btnEditar.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btnEditar.setText("Editar");
        pnlRegistroUsuAdminMain.add(btnEditar);
        btnEditar.setBounds(370, 420, 230, 40);

        tpnMostrar.addTab("Registro Administrador", pnlRegistroUsuAdminMain);

        pnlRegistroUsuAdminMain1.setLayout(null);

        lblAgregaryCrearUsuario.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblAgregaryCrearUsuario.setText("AGREGAR Y CREAR USUARIO");
        pnlRegistroUsuAdminMain1.add(lblAgregaryCrearUsuario);
        lblAgregaryCrearUsuario.setBounds(50, 50, 220, 30);

        lblSubTitulo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubTitulo1.setText("• Creación de Usuario");
        pnlRegistroUsuAdminMain1.add(lblSubTitulo1);
        lblSubTitulo1.setBounds(70, 110, 150, 20);

        lblNombres.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblNombres.setText("Nombres:");
        pnlRegistroUsuAdminMain1.add(lblNombres);
        lblNombres.setBounds(70, 160, 60, 30);

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        pnlRegistroUsuAdminMain1.add(txtNombres);
        txtNombres.setBounds(130, 160, 190, 30);

        lblApellidos.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblApellidos.setText("Apellidos:");
        pnlRegistroUsuAdminMain1.add(lblApellidos);
        lblApellidos.setBounds(330, 160, 60, 30);
        pnlRegistroUsuAdminMain1.add(txtApellidos);
        txtApellidos.setBounds(390, 160, 190, 30);

        lblTelefono.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblTelefono.setText("Telefono:");
        pnlRegistroUsuAdminMain1.add(lblTelefono);
        lblTelefono.setBounds(70, 230, 60, 30);
        pnlRegistroUsuAdminMain1.add(txtTelefono);
        txtTelefono.setBounds(130, 230, 190, 30);

        lblDNIUsuario.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblDNIUsuario.setText("DNI/Usuario:");
        pnlRegistroUsuAdminMain1.add(lblDNIUsuario);
        lblDNIUsuario.setBounds(330, 230, 80, 30);
        pnlRegistroUsuAdminMain1.add(txtDNIUsuario);
        txtDNIUsuario.setBounds(410, 230, 170, 30);

        lblContraseña.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblContraseña.setText("Contraseña:");
        pnlRegistroUsuAdminMain1.add(lblContraseña);
        lblContraseña.setBounds(70, 300, 70, 30);
        pnlRegistroUsuAdminMain1.add(txtContraseña);
        txtContraseña.setBounds(140, 300, 180, 30);

        lblTipoUsuario.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblTipoUsuario.setText("Tipo Usuario:");
        pnlRegistroUsuAdminMain1.add(lblTipoUsuario);
        lblTipoUsuario.setBounds(330, 300, 80, 30);

        cbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "empleado" }));
        pnlRegistroUsuAdminMain1.add(cbTipoUsuario);
        cbTipoUsuario.setBounds(410, 300, 170, 30);

        btnGuardaryAgregarDatos.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        btnGuardaryAgregarDatos.setText("Guardar y Agregar Datos");
        btnGuardaryAgregarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardaryAgregarDatosActionPerformed(evt);
            }
        });
        pnlRegistroUsuAdminMain1.add(btnGuardaryAgregarDatos);
        btnGuardaryAgregarDatos.setBounds(320, 390, 300, 50);

        rbtActivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbtActivo.setForeground(new java.awt.Color(102, 153, 0));
        rbtActivo.setSelected(true);
        rbtActivo.setText("ACTIVO");
        rbtActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtActivoActionPerformed(evt);
            }
        });
        pnlRegistroUsuAdminMain1.add(rbtActivo);
        rbtActivo.setBounds(140, 390, 100, 20);

        rbtInactivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbtInactivo.setForeground(new java.awt.Color(204, 0, 0));
        rbtInactivo.setText("INACTIVO");
        rbtInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtInactivoActionPerformed(evt);
            }
        });
        pnlRegistroUsuAdminMain1.add(rbtInactivo);
        rbtInactivo.setBounds(140, 420, 100, 20);

        tpnMostrar.addTab("Registro Administrador 1", pnlRegistroUsuAdminMain1);

        getContentPane().add(tpnMostrar);
        tpnMostrar.setBounds(190, 80, 690, 560);

        setSize(new java.awt.Dimension(894, 644));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarNombre(JLabel label) {
        JOptionPane.showMessageDialog(this, "el boton" + label.getText() + " FUNCIONA!!!");
    }

    private void btninicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninicioMouseClicked
        tpnMostrar.setSelectedIndex(0);
        
    }//GEN-LAST:event_btninicioMouseClicked

    private void btnAlmacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlmacenMouseClicked
        mostrarNombre(btnAlmacen);
    }//GEN-LAST:event_btnAlmacenMouseClicked

    private void btnregistrodecomprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrodecomprasMouseClicked
        mostrarNombre(btnAlmacen);
    }//GEN-LAST:event_btnregistrodecomprasMouseClicked

    private void btnregistrodeventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrodeventasMouseClicked
        mostrarNombre(btnregistrodeventas);
    }//GEN-LAST:event_btnregistrodeventasMouseClicked

    private void btncajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncajaMouseClicked
        mostrarNombre(btncaja);
    }//GEN-LAST:event_btncajaMouseClicked

    private void btnregistrodeusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrodeusuarioMouseClicked
        actualizarTBLRegistroUsuarios();
        tpnMostrar.setSelectedIndex(1);
    }//GEN-LAST:event_btnregistrodeusuarioMouseClicked

    private void btnreportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreportesMouseClicked
        mostrarNombre(btnreportes);
    }//GEN-LAST:event_btnreportesMouseClicked

    private void btnajustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajustesMouseClicked
        mostrarNombre(btnajustes);
    }//GEN-LAST:event_btnajustesMouseClicked

    private void btncerrarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarsesionMouseClicked
        mostrarNombre(btncerrarsesion);
    }//GEN-LAST:event_btncerrarsesionMouseClicked

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        // TODO add your handling code here:
        tpnMostrar.setSelectedIndex(2);
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    private void btnGuardaryAgregarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardaryAgregarDatosActionPerformed
        String errorMensaje="";
        Integer telefono=ConvertidorUsuario.tryParseTelefono(txtTelefono.getText());
        Integer usuarioDNI=ConvertidorUsuario.tryParseUsuarioDNI(txtDNIUsuario.getText());
        if(telefono==null||usuarioDNI==null){
            if(telefono==null){
                errorMensaje+="Formato de telefono no valido.\n";
            }
            if(usuarioDNI==null){
                errorMensaje+="Formato de DNI no valido.\n";
            }
            JOptionPane.showMessageDialog(this, errorMensaje);
            return;
        }
        boolean esCuentaInactiva=rbtInactivo.isSelected();
        
        baseDeDatos.crearCuentaUsuario(usuarioDNI, txtNombres.getText(),txtApellidos.getText() , Integer.parseInt(txtTelefono.getText()), txtContraseña.getText(), cbTipoUsuario.getSelectedItem().toString(),esCuentaInactiva);
        actualizarTBLRegistroUsuarios();
    }//GEN-LAST:event_btnGuardaryAgregarDatosActionPerformed

    private void rbtActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtActivoActionPerformed
        rbtActivo.setSelected(true);
        rbtInactivo.setSelected(false);
        
    }//GEN-LAST:event_rbtActivoActionPerformed

    private void rbtInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtInactivoActionPerformed
        rbtInactivo.setSelected(true);
        rbtActivo.setSelected(false);
        
    }//GEN-LAST:event_rbtInactivoActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuDinamico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAlmacen;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardaryAgregarDatos;
    private javax.swing.JLabel btnajustes;
    private javax.swing.JLabel btncaja;
    private javax.swing.JLabel btncerrarsesion;
    private javax.swing.JLabel btninicio;
    private javax.swing.JLabel btnregistrodecompras;
    private javax.swing.JLabel btnregistrodeusuario;
    private javax.swing.JLabel btnregistrodeventas;
    private javax.swing.JLabel btnreportes;
    private javax.swing.JComboBox<String> cbTipoUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpaneladmin;
    private javax.swing.JPanel jpanelgeneral;
    private javax.swing.JPanel jpanelsuperior;
    private javax.swing.JLabel lblAgregaryCrearUsuario;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblCompraDelMes;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblDNIUsuario;
    private javax.swing.JLabel lblGanancias;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblProveedores;
    private javax.swing.JLabel lblRUC;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblSubTitulo1;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JLabel lblVentasDelDia;
    private javax.swing.JLabel lblimagen1;
    private javax.swing.JLabel lblimagen2;
    private javax.swing.JLabel lblinventario;
    private javax.swing.JPanel pnl1Inicio;
    private javax.swing.JPanel pnlCientes;
    private javax.swing.JPanel pnlCompraDelMes;
    private javax.swing.JPanel pnlGancias;
    private javax.swing.JPanel pnlProductos;
    private javax.swing.JPanel pnlProveedores;
    private javax.swing.JPanel pnlRegistroUsuAdminMain;
    private javax.swing.JPanel pnlRegistroUsuAdminMain1;
    private javax.swing.JPanel pnlVentasDelDia;
    private javax.swing.JRadioButton rbtActivo;
    private javax.swing.JRadioButton rbtInactivo;
    private javax.swing.JTable tblRegistroUsuarios;
    private javax.swing.JTabbedPane tpnMostrar;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtClientes;
    private javax.swing.JTextField txtComprasDelMes;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtDNIUsuario;
    private javax.swing.JTextField txtGanancias;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtProductos;
    private javax.swing.JTextField txtProveedores;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtVentasDelDia;
    // End of variables declaration//GEN-END:variables
}
